name: Lint Dockerfiles

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker run --rm -i -v $(pwd):$(pwd) -w $(pwd) hadolint/hadolint < Dockerfile
