name: Lint Dockerfiles

on: [push, pull_request]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: brew install hadolint
      - run: hadolint Dockerfile
